### ISSUE TITLE
Cannot import phoenix.json via github repository extension editing

### ISSUE THREAD

**Issue by EnderNate** [FRC-4509-MechBulls/2022_Rapid_React_Bot#1]
I think there is a way to just manually put the file in vendordeps yourself, but im not sure how to do that. Last year @NatashaSetiadi  had a tinyurl that took you straight to it, but I dont know if that link is still usable because it is the 2020 version, not the 2022 version. 

Also this issue is just me testing out github features so yeh

**Comment by NatashaSetiadi** [comment]
Yea I did, my link was tinyurl.com/Phoenixjson or https://maven.ctr-electronics.com/release/com/ctre/phoenix/Phoenix-latest.json

**Comment by EnderNate** [comment]
Is that a new version or is it still the old one?

**Comment by NatashaSetiadi** [comment]
I'm not sure if it's the new version, although the url does say Phoenix-latest.json so perhaps it automatically takes the latest version

**Comment by EnderNate** [comment]
im kinda dumb, i coulda just copy pasted from one of my other projects 

that link is an old version, but the new version provides a correct link inside it so yeah
